In [34]:
import pandas as pd

In [35]:
df=pd.read_csv("C:\\Users\\Amjad Net Cafe\Desktop\\Kamyab jawan data science\\Pokemon.csv")

In [37]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

# Average Speed

In [38]:
Speed_mean = df["Speed"].mean()

In [39]:
Speed_mean

68.2775

# Function to find low and high speed

In [40]:
def Check_speed(value):
    if(value > Speed_mean):
        return "High_Speed"
    else:
        return "Low_Speed"

# Add High_low_speed

In [41]:
df["Speed_High_Low"] = df["Speed"].apply(Check_speed)

In [42]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed_High_Low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low_Speed
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low_Speed
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High_Speed
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High_Speed
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low_Speed
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,High_Speed
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,High_Speed
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,High_Speed
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,High_Speed
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Low_Speed

# Average HP

In [43]:
HP_mean = df["HP"].mean()

# Find low and high HP

In [44]:
def Check_HP(value):
    if(value > HP_mean):
        return "High_HP"
    else:
        return "Low_HP"

# Add high_low_HP

In [45]:
df["High_Low_HP"] = df["HP"].apply(Check_HP)

In [46]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed_High_Low,High_Low_HP
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low_Speed,Low_HP
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low_Speed,Low_HP
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High_Speed,High_HP
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High_Speed,High_HP
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low_Speed,Low_HP
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,High_Speed,Low_HP
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,High_Speed,High_HP
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,High_Speed,High_HP
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,High_Speed,High_HP
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Low_Speed,Low_HP